shopgate/theme-ios11

- components/TextField/style.js
- components/View/style.js
- pages/Cart/components/CouponField/components/Layout/style.js
- reseted paddings on some inputs
- removed the background color from the scroll container
> CON-2223: input field fixes

- components/Dialog/index.jsx
- setted TestMessageDialog component as default, when a message, but no
type is passed through the params
> CON-2622: changed DialogComponent type handling

- components/CategoryList/connector.js
- npm-shrinkwrap.json
- pages/Category/connector.js
- replaced the routed connect helper by the original redux connect
> CON-2558 Fixed broken category lists on back navigation

- components/Navigator/components/Content/components/Title/index.jsx
- components/ProductCard/style.js
- pages/Product/components/Description/index.jsx
- pages/Product/components/Description/style.js
- pages/Product/components/Header/components/Manufacturer/index.jsx
- pages/Product/components/Header/components/Manufacturer/style.js
- pages/Product/components/Header/components/Name/style.js
- pages/Product/components/Header/components/Price/style.js
- pages/Product/components/Header/components/PriceInfo/style.js
- pages/Product/components/Header/components/PriceStriked/style.js
- pages/Product/components/Header/index.jsx
- pages/Product/components/Header/style.js
- pages/Product/components/Properties/index.jsx
- pages/Product/components/Properties/style.js
- fixed misaligned misaligned strike prices at product slider widgets
- fixed wrong header title when navigating back to the browser page
> CON-2703 Added some typography adjustments to the Product page

- widgets/Html/index.jsx
- widgets/Html/style.js
- removed touchStart event listener from links
- added clearfix to avoid display issues at sibling widgets
> CON-2368: HTML widget bugfixes

- components/View/connector.js
- components/View/index.jsx
- pages/Product/connector.js
- replaced the routeWillEnter logic from RoutedConnect by a history
state based approach
> CON-2824: Fixed an issue that prevented Navigator title updates

- components/MessageBar/index.jsx
- components/MessageBar/spec.jsx
- pages/Cart/components/Item/components/Coupon/index.jsx
- pages/Cart/components/Item/components/Product/index.jsx
- pages/Cart/components/Item/index.jsx
- pages/Cart/components/Item/style.js
PI-8146 show cart item messages
> PI-8146 show cart item messages

- components/Navigator/style.js
- components/Sheet/style.js
- components/TabBar/style.js
- components/View/style.js
- components/Viewport/selectors.js
- components/Viewport/style.js
- components/Viewport/subscriptions.js
- pages/Cart/components/PaymentBar/style.js
- pages/Filter/style.js
- pages/ProductGallery/style.js
- pages/subscribers.js
- styles/variables.js
- replaced default safe-area environment css insets by custom ones
> CON-2826: Fixed overlapping of the NavigationBar by the device status bar

- pages/Product/actions/getProductData.js
> PI-8297: Feedback

- pages/Product/components/VariantSelects/components/ProductVariants/__snapshots__/spec.jsx.snap
- pages/Product/components/VariantSelects/components/ProductVariants/index.jsx
- pages/Product/components/VariantSelects/connector.js
- pages/Product/components/VariantSelects/index.jsx
PI-8236 added logic to sync current variant state between redux and component state
> PI-8236 added logic to sync current variant state between redux and component state

- components/Viewport/style.js
- pages/Product/components/Description/style.js
- styles/index.js
- the user now can't trigger the text selection tool anymore by long pressing at text elements
> PI-8206: Deactivated text selection globally

- package.json
- pages/Browse/components/SearchField/__snapshots__/spec.jsx.snap
- pages/Browse/components/SearchField/components/Suggestions/components/Suggestion/index.jsx
- pages/Browse/components/SearchField/components/Suggestions/connector.js
- pages/Browse/components/SearchField/components/Suggestions/constants.js
- pages/Browse/components/SearchField/components/Suggestions/index.jsx
- pages/Browse/components/SearchField/components/Suggestions/spec.jsx
- pages/Browse/components/SearchField/index.jsx
- pages/Browse/components/SearchField/spec.jsx
- pages/Browse/index.jsx
- pages/Browse/subscriptions.js
- pages/subscribers.js
- the search suggestions overlay now disappears when the browse page is left
- added a minimum character about from which search suggestions are requested
> CON-2774: Fixed some search issues

- extension-config.json
- add productPropertiesFilter feature flag to extension-config
> CON-2842: Only whitelisted properties are shown on product pages

- components/ContextMenu/index.jsx
- components/ImageSlider/index.jsx
- components/ProductCard/index.jsx
- components/ProductGrid/components/Item/index.jsx
- components/ProductList/components/Item/index.jsx
- components/Reviews/components/AllReviewsLink/index.jsx
- pages/Cart/components/Item/components/Product/index.jsx
- pages/Product/actions/getProductData.js
- pages/Product/components/VariantSelects/components/ProductVariants/__snapshots__/spec.jsx.snap
- pages/Product/components/VariantSelects/components/ProductVariants/index.jsx
- pages/Product/components/VariantSelects/connector.js
- pages/Product/subscriptions.js
- widgets/Liveshopping/index.jsx
Reverts shopgate/theme-ios11#98
> Revert "CON-2003 open products from cart"

- components/ContextMenu/index.jsx
- components/ImageSlider/index.jsx
- components/ProductCard/index.jsx
- components/ProductGrid/components/Item/index.jsx
- components/ProductList/components/Item/index.jsx
- components/Reviews/components/AllReviewsLink/index.jsx
- pages/Cart/components/Item/components/Product/index.jsx
- pages/Product/actions/getProductData.js
- pages/Product/components/VariantSelects/components/ProductVariants/__snapshots__/spec.jsx.snap
- pages/Product/components/VariantSelects/components/ProductVariants/index.jsx
- pages/Product/components/VariantSelects/connector.js
- pages/Product/subscriptions.js
- widgets/Liveshopping/index.jsx
Reverts shopgate/theme-ios11#100
> Revert "Revert "CON-2003 open products from cart""

- widgets/Html/helpers/handleDOM.js
- widgets/Html/index.jsx
> DTY-56: Youtube video plays in cart without reason

- pages/Browse/constants.js
- pages/Browse/index.jsx
- add constants for portal
- add portals for browse.category-list(.before/.after)
> PWA-114: Add portals around category list

- components/ProductGrid/components/Item/index.jsx
- pages/Filter/__snapshots__/spec.jsx.snap
- pages/Filter/index.jsx
- pages/Filter/mock.js
- pages/Filter/spec.jsx
- filter price range portal
- portal for price in grid item
> PWA-218: Add portals to prices on category page

- locale/index.js
- now matches the method signature of the helper module within common
> PWA-293: Updated the parameter order of the mergeTranslations call

- components/ProductGrid/components/Item/style.js
- adjust zIndex of favlist button in lists
> PWA-198: heart icon / fav list icon is above sort bar

- locale/de-DE.json
- locale/en-US.json
- locale/fr-FR.json
- pages/Cart/components/Item/components/Coupon/components/Layout/components/CouponFreeShipping/index.jsx
- pages/Cart/components/Item/components/Coupon/components/Layout/index.jsx
@sznowicki 
If you are not able to do the review please let me know.
Thanks
Aaron
> Ccp 636 free shipping coupon from magento

- pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/__snapshots__/spec.jsx.snap
- pages/Cart/components/PaymentBar/components/Content/components/CheckoutButton/index.jsx
- now the button looks disabled agein when the checkout is not possible
> PWA-612: Fix to disable the checkout button visually

- pages/Product/components/AddToCartBar/__snapshots__/index.spec.jsx.snap
- pages/Product/components/AddToCartBar/components/AddMoreButton/index.jsx
- pages/Product/components/AddToCartBar/components/AddMoreButton/style.js
- pages/Product/components/AddToCartBar/index.jsx
- pages/Product/components/AddToCartBar/index.spec.jsx
- the AddMoreButton now renders the original AddToCartButton which offers in improved UX
> PWA-678: Refactored AddToCartBar to use the AddToCartButton

- pages/Product/subscriptions.js
- pages/Reviews/subscriptions.js
- pages/WriteReview/spec.jsx
- fixed a console warning inside the Review page test
> PI-8930: Equalized review order on PDP and review page
